Import sage.all initiall so that imports resolve correctly
otherwise we get a
```
import: 'surface_dynamics'

Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/surface-dynamics_1564390545642/test_tmp/run_test.py", line 2, in <module>
    import surface_dynamics
  File ".../surface_dynamics/__init__.py", line 21, in <module>
    from .topology.all import *
  File ".../surface_dynamics/topology/all.py", line 10, in <module>
    from .fat_graph import FatGraph
  File ".../surface_dynamics/topology/fat_graph.py", line 19, in <module>
    from sage.rings.integer_ring import ZZ
  File "sage/rings/integer.pxd", line 7, in init sage.rings.integer_ring (build/cythonized/sage/rings/integer_ring.c:17024)
  File "sage/rings/rational.pxd", line 8, in init sage.rings.integer (build/cythonized/sage/rings/integer.c:51949)
  File "sage/rings/rational.pyx", line 81, in init sage.rings.rational (build/cythonized/sage/rings/rational.c:39566)
ImportError: cannot import name ZZ
```